version: '3.9'
services:
    backend:
        build: .
        ports:
            - 8000:3000
        volumes:
            - .:/api
        depends_on:
            - db_cm_api

    db_cm_api:
        image: mysql:5.7
        restart: always
        environment:
          MYSQL_DATABASE: client_management_api
          MYSQL_USER: admin
          MYSQL_PASSWORD: dev
          MYSQL_ROOT_PASSWORD: dev
          MYSQL_TCP_PORT: 3101
        volumes:
          - .dbdata:/var/lib/mysql-db-cm-api
        ports:
          - 31101:3101